ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1000
ARG PGID=1000
#
RUN set -xe \
    && addgroup -g ${PGID} -S alpine \
    && adduser -u ${PUID} -G alpine -h /var/lib/coturn -D alpine \
    && apk add --no-cache --purge -uU \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        coturn sqlite-libs \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME /var/lib/coturn/
#
EXPOSE 3478/udp 3478/tcp 3480/udp 3480/tcp
#
ENTRYPOINT ["/init"]
