#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

COTURN_DATADIR="${COTURN_DATADIR:-/var/lib/coturn}";
COTURN_CONF="${COTURN_CONF:-$COTURN_DATADIR/turnserver.conf}";

vecho "Ensure configuration directories exist.";
mkdir -p \
    $(dirname ${COTURN_CONF}) \
    ${COTURN_DATADIR} \
    ;

_subst () {
    sed \
    -e "s|COTURN_DATADIR|$COTURN_DATADIR|g" \
    -e "s|COTURN_CLIPASSWORD|${COTURN_CLIPASSWORD:-CHANGE_ME}|g" \
    -e "s|COTURN_CERTFILE|${COTURN_CERTFILE:-/etc/ssl/certs/cert.pem}|g" \
    -e "s|COTURN_PKEYFILE|${COTURN_PKEYFILE:-/etc/ssl/private/privkey.pem}|g" \
    -e "s|COTURN_LISTENADDR|${COTURN_LISTENADDR:-0.0.0.0}|g" \
    -e "s|COTURN_REALM|${COTURN_REALM:-localhost}|g" \
    $1 > $2;
}

# ensure turnserver conf exists
if [ ! -f "${COTURN_CONF}" ];
then
    vecho "Setting up default configuration as ${COTURN_CONF}.";
    _subst /defaults/turnserver.conf ${COTURN_CONF};
fi;

# fix permissions
if [ -z "${COTURN_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown -R ${S6_USER:-alpine}:${PGID:-1000} \
        ${COTURN_DATADIR} \
        ${COTURN_CONF} \
        $(dirname ${COTURN_CONF}) \
        ;
fi;
